#!/usr/bin/env python

import sys
from redis import Redis

#$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
#ip, port = $1, $2
#ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
#port = port.nil? ? 6379 : port
ip, port = "127.0.0.1", 6379

if 'config' in sys.argv:
  print "graph_title Redis Connections rate"
  print "graph_category redis"
  print "graph_vlabel connections/s"
  print "graph_info This graph monitors the connctions rate"

  print "connections.label connections"
  print "connections.type COUNTER"
  print "connections.min 0"
else:
  redis = Redis(host=ip, port=port)
  info  = redis.info()

  print "connections.value" + " " + str(info['total_connections_received'])
