#!/usr/bin/env python

import sys
from redis import Redis

#$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
#ip, port = $1, $2
#ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
#port = port.nil? ? 6379 : port
ip, port = "127.0.0.1", 6379

if 'config' in sys.argv:
  print "graph_title Redis Clients"
  print "graph_category redis"
  print "graph_vlabel connections/s"
  print "graph_info This graph monitors the number of clients"

  print "clients.label clients"
  print "clients.type GAUGE"
  print "clients.min 0"
else:
  redis = Redis(host=ip, port=port)
  info  = redis.info()

  print "clients.value" + " " + str(info['connected_clients'] - 1)
