#!/usr/bin/env python

import os
import sys
from redis import Redis

#$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
#ip, port = $1, $2
#ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
#port = port.nil? ? 6379 : port
ip, port = "127.0.0.1", 6379

if 'config' in sys.argv:
  print "graph_title Redis Commands rate"
  print "graph_category redis"
  print "graph_vlabel commands/s"
  print "graph_info This graph monitors the commands rate"

  print "commands.label commands/s"
  print "commands.type COUNTER"
  print "commands.min 0"
else:
  redis = Redis(host=ip, port=port, password=os.environ.get('REDIS_PASS'))
  info  = redis.info()

  print "commands.value" + " " + str(info['total_commands_processed'])
