#!/usr/bin/env python

import sys
from redis import Redis

#$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
#ip, port = $1, $2
#ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
#port = port.nil? ? 6379 : port
ip, port = "127.0.0.1", 6379

infos = {}
for k, v in Redis(host=ip, port=port).info().items():
    if k.startswith("db"):
        infos[k] = v

if 'config' in sys.argv:
  print "graph_title Redis Keys"
  print "graph_category redis"
  print "graph_info Display the number of keys by DB"
  print "graph_args -l 0"

  area_done = False
  for db, info in infos.items():
    type = 'STACK'
    if not area_done:
      type = 'AREA'
      area_done = True
    print "%s_keys.label %s_keys" % (db, db)
    print "%s_keys.info db %s" % (db, db)
    print "%s_keys.type GAUGE" % db
    print "%s_keys.min 0" % db
    print "%s_keys.draw %s" % (db, type)

    print "%s_expires.label %s_expires" % (db, db)
    print "%s_expires.info db %s" % (db, db)
    print "%s_expires.type GAUGE" % db
    print "%s_expires.min 0" % db
    print "%s_expires.draw STACK" % db
else:
  for db, info in infos.items():
    print "%s_keys.value %d" % (db, info['keys'])
    print "%s_expires.value %d" % (db, info['expires'])
