#!/usr/bin/env python

import sys
from redis import Redis

#$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
#ip, port = $1, $2
#ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
#port = port.nil? ? 6379 : port
ip, port = "127.0.0.1", 6379

if 'config' in sys.argv:
  print "graph_title Redis Changes since last save"
  print "graph_category redis"

  print "changes.label changes"
else:
  redis = Redis(host=ip, port=port)
  info  = redis.info()

  print "changes.value" + " " + str(info['changes_since_last_save'])
