#!/usr/bin/env python

import os
import sys
from redis import Redis

#$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
#ip, port = $1, $2
#ip     = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
#port   = port.nil? ? 6379 : port
ip, port = "127.0.0.1", 6379

if 'config' in sys.argv:
  print "graph_title Redis Memory"
  print "graph_category redis"
  print "graph_vlabel mem used"
  print "graph_info This graph monitors the commands rate"
  print "graph_args --base 1024 -l 0"

  print "memory.label memory"
  print "memory.info Amount of mem used by redis"
  print "memory.type GAUGE"
  print "memory.min 0"
  print "memory.draw AREA"

else:
  redis = Redis(host=ip, port=port, password=os.environ.get('REDIS_PASS'))
  info  = redis.info()

  print "memory.value" + " " + str(info['used_memory'])
